#!/bin/bash

# Source the secrets file to load the API_KEY and API_SECRET
source secret.txt

# Constants
API_URL="https://api.godaddy.com/v1/domains"
LIMIT=1000                     # Maximum number of domains per page
RATE_LIMIT_DELAY=5             # Time to wait between API calls to respect rate limits
TEMP_FILE="domains.json"       # Temporary file to store the response
marker=5                      # Start marker for pagination, initially empty

curl -s -X GET "$API_URL?limit=$LIMIT&marker=$marker" -H "Authorization: sso-key $API_KEY:$API_SECRET" -H "accept: application/json" -H "Content-Type: application/json" | jq . > $TEMP_FILE